### ISSUE TITLE
Great Icons

### ISSUE THREAD

**Issue by KordonDev** [KordonDev/relay-race-web#13]
Redo my crapy icons
- [ ] [waypoint-minus.svg](https://github.com/KordonDev/relay-race-web/blob/master/public/assets/waypoint-minus.svg)
- [ ] [waypoint-plus.svg](https://github.com/KordonDev/relay-race-web/blob/master/public/assets/waypoint-plus.svg)

This was the inspiration https://github.com/KordonDev/relay-race-web/blob/master/public/assets/icons8-reise-24.png

**Comment by Safi1012** [comment]
<img width="484" alt="Screen Shot 2020-04-14 at 21 40 44" src="https://user-images.githubusercontent.com/3514796/79266924-9fd6ba80-7e98-11ea-8bc8-869fd1459472.png">


[icons.zip](https://github.com/KordonDev/relay-race-web/files/4477364/icons.zip)
